Improve signup/login modal functionality
codersforcauses/coexist pull request #106
Opened 2024-07-28 15:35 UTC by harryrigg

## Change Summary
- Changed signup/login modals so that parent component is not required to keep opened/closed state

2024-08-01 10:36 UTC, dct0 approved these changes

2024-08-03 07:12 UTC, K-Straiton requested changes
This is a very old version of the modal that has been changed. Main will need to be merged into this branch and conflicts need to be resolved.

2024-08-03 07:26 UTC, CodeWithTheDoctor commented
Update - I have merged main into the branch and resolved the conflicts for you @harryrigg :)

2024-08-03 07:26 UTC, K-Straiton approved these changes

2024-08-03 07:26 UTC, merged