Issue 32 create profile page
codersforcauses/coexist pull request #35
Opened 2024-06-30 13:47 UTC by SetroZ

## Change Summary
Created profile page, switched `<a>` to `<Link>`
 in navbar, created Nav title to display text in main page only, moved nav to layout

### Change Form

- [x] The pull request title has an issue number
- [x] The change works by "Smoke testing" or quick testing
- [x] The change has tests
- [ x] The change has documentation

## Other Information
Awaiting for colors PR to be done.

2024-07-07 15:00 UTC, K-Straiton requested changes
Looks good. I have added comments for some changes for border radius, so it is consistent with signup and login modals, as well as for extra margin on desktop.

2024-07-08 05:14 UTC, dct0 approved these changes

2024-07-08 05:45 UTC, K-Straiton approved these changes

2024-07-08 05:45 UTC, K-Straiton commented
Awesome! Feel free to merge!

2024-07-08 06:06 UTC, merged