Issue 48 convert colours in global css to hex
codersforcauses/coexist pull request #51
Opened 2024-07-06 09:53 UTC by KKatariah

## Change Summary
Changed tailwind config from --hsl convert to --hex.
Changed globals.css colours from hsl to hex.

### Change Form
- [x] The pull request title has an issue number
- [x] The change works by "Smoke testing" or quick testing
- [ ] The change has tests
- [ ] The change has documentation

## Other Information
N/A

2024-07-06 13:32 UTC, dct0 approved these changes

2024-07-06 13:40 UTC, dct0 requested changes
The colours aren't working on the preview deployment. I took a look at the tailwind docs https://tailwindcss.com/docs/customizing-colors#using-css-variables and it looks like the css variables only work with rgb/hsl. Maybe you could try `var(--variable)` instead? If that doesn't work, you have two options: rgb or remove the css variables. For the second one, you can just put the hex colour in the tailwind config and remove the css variable. The caveat is there won't be a dark mode but we don't have a design for that anyway so no big deal

2024-07-17 04:30 UTC, KKatariah commented
changed from hex to rgb values since the previews work in VSC and people are more familiar with it than hsl anyway

2024-07-20 03:52 UTC, K-Straiton commented
Unfortunately, in order to have the colour previews in the global.css it needs to have the colour space, however tailwind doesn't work when the colourspace is specified. Better to keep is as is for now. Closing the issue.

2024-07-20 03:52 UTC, closed without merging