Issue 61 connect sign up modal to backend
codersforcauses/coexist pull request #94
Opened 2024-07-21 08:16 UTC by jasonkeo

## Change Summary
-added front end check to signup form
-added sign out to profile
-created create user api

### Change Form
**Fill this up (NA if not available). If a certain criteria is not met, can you please give a reason.**

- [ ] The pull request title has an issue number
- [ ] The change works by "Smoke testing" or quick testing
- [ ] The change has tests
- [ ] The change has documentation

## Other Information
**[Is there anything in particular in the review that I should be aware of?]**

2024-07-21 09:12 UTC, jasonkeo commented
ok idk why but when i went to merge some stuff from main some of the error messages broke so im just gonan leave it like dis

2024-07-22 11:08 UTC, dct0 requested changes
Looks good, some small comments

2024-07-22 11:08 UTC, dct0 commented on client/src/components/ui/SignUpModal.tsx
> +    // front end checks for empty field and password
I would move this validation into a separate function to keep things tidy

2024-07-22 11:08 UTC, dct0 commented on client/src/components/ui/SignUpModal.tsx
> +  const [phone, setPhone] = useState("");
Make sure these variables are camelCase

2024-07-22 11:08 UTC, dct0 commented on client/src/components/ui/SignUpModal.tsx
> +  let [emsg, setMsg] = useState(Array(5).fill(false));
These should be consts because they don't get reassigned

2024-07-23 09:50 UTC, dct0 approved these changes

2024-07-23 10:01 UTC, merged